### ISSUE TITLE
nmi returns status 500 with error "failed to match pod IP with []"   

### ISSUE THREAD

**Issue by dsbrng25b** [Azure/aad-pod-identity#761] opened 2020-08-26 13:31 UTC
**Describe the bug**
We get a "list pod error" but it does not only shows <nil> instead of the error message.
```
W0826 11:28:42.030149       1 client.go:207] list pod error: <nil>. Retrying, attempt number: 1                                                                                                             
W0826 11:28:42.330387       1 client.go:207] list pod error: <nil>. Retrying, attempt number: 2                                                               
W0826 11:28:42.630557       1 client.go:207] list pod error: <nil>. Retrying, attempt number: 3                                                                                                             W0826 11:28:42.930889       1 client.go:207] list pod error: <nil>. Retrying, attempt number: 4                                                                                                             
E0826 11:28:43.231164       1 server.go:341] failed to get pod info from pod IP: 10.240.0.234, error failed to match pod IP 10.240.0.234 with []                                                            
I0826 11:28:43.231215       1 server.go:190] status (500) took 1201122525 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.240.0.234
```

**Expected behavior**
nmi shows the reason for the error.

**AAD Pod Identity version**
1.6.2

**Kubernetes version**
1.16.13

**Comment by chewong** [comment] 2020-08-26 16:05
Hi @dsbrng25b, curious about your AKS cluster setup. Did you limit your cluster's egress traffic? We have been trying to reproduce the problem you are encountering but wasn't able to.

**Comment by dsbrng25b** [comment] 2020-08-27 07:28
@chewong here you find the answers to your questions. hope this helps. I saw the error for the first time and unfortunately I couldn't see the original error message so it is difficult to reproduce the problem.

>     * Did you limit your cluster's egress traffic?
no

>     * how old is your cluster?
I guess the cluster got created half a year ago

>     * which region is it deployed to?
west europe

>     * how many nodes and what are their SKUs?
one node pool with 3 Standard_D4s_v3 nodes

>     * What do your AzureIdentity and AzureIdentityBinding look like?
to create the AzureIdentity and the AzureIdentityBinding we use the following template:
```
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: $NAME
  namespace: $NAMESPACE
spec:
  type: 0
  resourceID: $IDENTITY_RESOURCE_ID
  clientID: $IDENTITY_CLIENT_ID
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: $NAME
  namespace: $NAMESPACE
spec:
  azureIdentity: $NAME
  selector: $NAME
```

**Comment by aramase** [comment] 2020-08-28 20:29
@dsbrng25b Did the pod token request succeed in the next attempt?

**Comment by billpieper** [comment] 2020-09-01 21:55
I have experienced this same issue today with two different AKS clusters.  Both seemed to happen in the situation where during a deployment, the cluster auto scaling added a node to the cluster during deployment of an updated helm chart for our app.

The problem did correct itself -- but it took a quite a few minutes to do so.  I captured the pod log from the nmi pod on the node where the issue was happening and am attaching it.

kubernetes version = 1.17.9
aad pod identity version = 1.6.2
deployed region = eastus2

[nmi.log](https://github.com/Azure/aad-pod-identity/files/5159025/nmi.log)

**Comment by aramase** [comment] 2020-09-01 22:12
@billpieper This looks like an issue with the api server not able to respond to the request - 
```
W0901 21:44:16.854985       1 reflector.go:326] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: watch of *v1.AzurePodIdentityException ended with: an error on the server ("unable to decode an event from the watch stream: read tcp 172.17.32.85:37184->172.17.2.1:443: read: connection timed out") has prevented the request from succeeding
W0901 21:44:16.855029       1 reflector.go:326] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: watch of *v1.Pod ended with: an error on the server ("unable to decode an event from the watch stream: read tcp 172.17.32.85:37184->172.17.2.1:443: read: connection timed out") has prevented the request from succeeding
W0901 21:44:16.854985       1 reflector.go:326] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: watch of *v1.AzureAssignedIdentity ended with: an error on the server ("unable to decode an event from the watch stream: read tcp 172.17.32.85:37184->172.17.2.1:443: read: connection timed out") has prevented the request from succeeding
```

After the connection timed out, it was reset and that resolved the issue.

**Comment by chewong** [comment] 2020-09-02 00:31
Closing this issue in favor of #780.

**Closed by chewong** 2020-09-02 00:31 UTC
Labels: bug
