### ISSUE TITLE
Demo app does not work on reinstall

### ISSUE THREAD

**Issue by lbicknese** [Azure/aad-pod-identity#800] opened 2020-09-21 18:39 UTC
**Have you**

- [x] Read [Troubleshooting Guide](../../docs/readmes/README.troubleshooting.md)
- [x] Read [Known Issues](../../docs/readmes/README.known-issues.md)
- [x] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**

Follwed the install instructions in the [README](https://github.com/Azure/aad-pod-identity). After installing it appeared to work, but I wanted to move to a different namespace. Deleted everything and reinstalled, and now the demo pod does not log as expected.

**Steps To Reproduce**

1. Follow instructions from README, but do not specify a namespace for helm install. Everything installed in demo namespace.
2. Delete all created resources.
3. Follow instructions again, but install in `namespace=kube-system`. Pod is installed in demo namespace.
4. Demo output hangs after output on line 33.

**Expected behavior**

Output from demo should contain success messages.

**AAD Pod Identity version**

v1.6.3

**Kubernetes version**

1.17.9

**Additional context**

[aad-pod-identity.txt](https://github.com/Azure/aad-pod-identity/files/5257501/aad-pod-identity.txt)

**Comment by aramase** [comment] 2020-09-21 18:48
@lbicknese Could you check the MIC pod logs for errors? The `AzureAssignedIdentity` is in Created which could mean there were errors during identity assignment.

**Comment by lbicknese** [comment] 2020-09-21 21:02
There are errors in one of the MIC pods. I've attached the logs from the pod.

[logs-from-mic-in-aad-pod-identity-mic-64f845d78d-dkz2p.txt](https://github.com/Azure/aad-pod-identity/files/5258114/logs-from-mic-in-aad-pod-identity-mic-64f845d78d-dkz2p.txt)

**Comment by aramase** [comment] 2020-09-21 22:30
@lbicknese Looks like you're using the kubelet-identity as an identity for your demo pod - 
```
    clientID: <IDENTITY_CLIENT_ID>
    resourceID: /subscriptions/<SUBSCRIPTION_ID>/resourcegroups/MC_<RESOURCE_GROUP>_<CLUSTER_NAME>_eastus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<CLUSTER_NAME>-agentpool
```

All control plane components running on the worker node use the kubelet identity to interact with Azure. Typically the identity used by applications is different from the kubelet identity. MIC assigns and un-assigns identities when the pod using it is created/deleted. In this case MIC deleted the kubelet identity when the demo pod was first deleted which is the expected behavior. Now it's trying to use the same identity for auth with azure and the identity doesn't exist. Could you please re-assign the cluster identity manually back to the cluster and use a different identity for the demo/workloads?

@TomGeske Any idea why the identity isn't being automatically reconciled by the RP?

**Comment by aramase** [comment] 2020-09-21 22:32
cc @Miwithro

**Comment by lbicknese** [comment] 2020-09-22 12:59
@aramase You are correct I used the kubelet identity. I definitely can use a different identity in my case. However, I'm not sure how to re-assign the cluster identity manually. I can still see the identity in my managed identities and the roles assigned. Any suggestions on what I need to do to re-assign? Or would I be better off rebuilding a new cluster? Thanks for your help.

**Comment by lbicknese** [comment] 2020-09-22 16:49
@aramase I created a new cluster and created a new identity this time. However, I am still getting an error.

```
mic.go:1093] failed to update user-assigned identities on node aks-nodepool1-36890647-vmss (add [1], del [0], update[0]), error: failed to update identities for aks-nodepool1-36890647-vmss in MC_<RESOURCE_GROUP>_vtg-demo_eastus, error: compute.VirtualMachineScaleSetsClient#Update: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client 'a67840fa-0e38-4077-9eed-e2b299ba4f65' with object id 'a67840fa-0e38-4077-9eed-e2b299ba4f65' has permission to perform action 'Microsoft.Compute/virtualMachineScaleSets/write' on scope '/subscriptions/<SUBSCRIPTION_ID>/resourceGroups/MC_<RESOURCE_GROUP>_vtg-demo_eastus/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodepool1-36890647-vmss'; however, it does not have permission to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/assign/action' on the linked scope(s) '/subscriptions/<SUBSCRIPTION_ID>/resourcegroups/<RESOURCE_GROUP>/providers/microsoft.managedidentity/userassignedidentities/vtg-demo-identity' or the linked scope(s) are invalid."
```

I am creating the "Managed Identity Operator" and "Virtual Machine Contributor" for the kubelet identity as defined in https://github.com/Azure/aad-pod-identity/blob/master/hack/role-assignment.sh.

I created the new Identity and assigned "Reader" to the identity resource group as described in step 2.

I have aad-pod-identity installed in kube-system, as well as the AzureIdentity and AzureIdentityBinding.

The demo pod is deployed in the "demo" namespace.

**Comment by aramase** [comment] 2020-09-22 16:53
@lbicknese If the identity is not in `MC_` resource group, then you would need to assign `Managed Identity Operator` role to the identity resource group as well - https://github.com/Azure/aad-pod-identity/blob/master/hack/role-assignment.sh#L28-L32.

This is a detailed doc for all the required role assignments - https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.role-assignment.md

**Comment by lbicknese** [comment] 2020-09-22 17:07
@aramase I reviewed my commands, and I accidentally used <RESOURCE_GROUP> when creating my new identity. I created the "Managed Identity Operator" as described in the documentation for <RESOURCE_GROUP>. The demo pod is now reporting as expected. I really appreciate your help with all of this. Thank you.

**Comment by aramase** [comment] 2020-09-22 17:21
@lbicknese Glad it's working! I'm going to keep this issue open so we can get a response from the AKS team on why the kubelet identity wasn't reconciled after it was deleted in your previous cluster.

**Comment by aramase** [comment] 2020-09-24 16:19
@miwithro Did you get a chance to look at this?

**Comment by miwithro** [comment] 2020-09-24 18:53
@bingosummer can you verify?

**Comment by aramase** [comment] 2020-10-05 18:32
Closing this issue. @miwithro Please update the issue with your findings when you get a chance.

**Closed by aramase** 2020-10-05 18:32 UTC
Labels: aks, bug
