### ISSUE TITLE
Regularly hanging on Find VM in resource group

### ISSUE THREAD

**Issue by cwebbtw** [Azure/aad-pod-identity#195] opened 2019-04-17 20:33 UTC
**Scenario**

3 VM AKS cluster with RBAC enabled
aad-pod-identity installed and working for the most part

**Problem**

This happens regularly but eventually works again after a few hours:

*mic logs*
```
I0417 20:10:20.365984       1 crd.go:174] <id>
I0417 20:10:20.366000       1 crd.go:178] Creating assigned Id: <id>
I0417 20:10:20.638240       1 cloudprovider.go:132] Find <vm> in resource group: <resource group>
E0417 20:25:58.639157       1 vm.go:48] azure#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded
E0417 20:25:58.639219       1 mic.go:415] azure#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded
E0417 20:25:58.674349       1 mic.go:269] azure#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded
```

*nmi logs*
```
time="2019-04-17T20:33:46Z" level=error msg="no AzureAssignedIdentity found for pod:<pod here>, <nil>" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.114.5.69
time="2019-04-17T20:33:46Z" level=info msg="Status (403) took 171745354 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.114.5.69
time="2019-04-17T20:34:02Z" level=info msg="node(aks-agentpool-42571559-1) hostip(10.114.5.66) metadataaddress(169.254.169.254:80) nmiport(2579)"
time="2019-04-17T20:34:02Z" level=info msg="Rules for table(nat) chain(aad-metadata) rules(-N aad-metadata, -A aad-metadata ! -s 127.0.0.1/32 -d 169.254.169.254/32 -p tcp -m tcp --dport 80 -j DNAT --to-destination 10.114.5.66:2579, -A aad-metadata -j RETURN)"
time="2019-04-17T20:34:08Z" level=error msg="no AzureAssignedIdentity found for pod:<pod here>, <nil>" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.114.5.69
time="2019-04-17T20:34:08Z" level=info msg="Status (403) took 19609807 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.114.5.69
```

Today it's being especially bad and hanging for long periods of time and eventually throwing. 

I haven't posted the identity and binding yaml definitions as this isn't a problem with getting the functionality working, rather a problem with having it consistently working.

**Comment by cwebbtw** [comment] 2019-04-18 13:29
Happening again after working for most of the morning (BST):

```
E0418 13:10:21.183500       1 vm.go:48] Long running operation terminated with status 'Failed': Code="InternalExecutionError" Message="An internal execution error occurred."
E0418 13:10:21.183587       1 cloudprovider.go:121] Long running operation terminated with status 'Failed': Code="InternalExecutionError" Message="An internal execution error occurred."
E0418 13:10:21.183615       1 mic.go:443] Long running operation terminated with status 'Failed': Code="InternalExecutionError" Message="An internal execution error occurred."
E0418 13:10:21.183644       1 mic.go:236] Binding <binding> removal from node aks-agentpool-42571559-2 for pod <pod> resulted in error Long running operation terminated with status 'Failed': Code="InternalExecutionError" Message="An internal execution error occurred."
```

**Comment by kkmsft** [comment] 2019-04-18 22:36
Since there are some thumbs up for these ? Are other folks also facing this issue ? 

@cwebbtw - Thank you for using aad-pod-identity. 
Have not seen this in my setups. Which region is your cluster in ?
If there is a test environment also where you are observing this. In which case, can you please try [Debugging](https://github.com/Azure/aad-pod-identity/wiki/Debugging) and enable more verbosity and notice any further information.

**Comment by cwebbtw** [comment] 2019-04-19 06:52
Our cluster is in westeurope. I will enable debugging and try to provide more detail when this next happens.

**Comment by khenidak** [comment] 2019-04-22 17:51
@cwebbtw 
This seems like timeouts cluster to ARM api. This can be due to multiple reasons such as bastion hosts, ARM rate limiting. Few things will help us help you:

1- Are you running any bastion/firewall hosts in this VNET?
2- How many clusters (and how big) are in the same Azure subscription?

**Comment by cwebbtw** [comment] 2019-04-22 19:30
Update

Haven't been able to provide debugging logs due to bank holiday weekend in the UK.

Answers to Khenidak's questions:

**1- Are you running any bastion/firewall hosts in this VNET?**
No, this virtual network does not have any bastion/firewall hosts.

**2- How many clusters (and how big) are in the same Azure subscription?**
There are two clusters, each scaled to 3 nodes .

**3- what VM sku mic is running on? is it over subscribed?**
VM type: Standard DS4 v2 (8 vcpus, 28 GB memory)

I'm not aware that it is over subscribed, we've seen this problem on DS2_V2 as well.

**Comment by cwebbtw** [comment] 2019-05-07 12:19
We're seeing:
```
time="2019-05-07T12:16:06Z" level=info msg="Status (403) took 30099842 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.114.5.10
time="2019-05-07T12:16:27Z" level=info msg="Status (200) took 5307290 ns" req.method=GET req.path=/metadata/instance req.remote=10.114.5.34
time="2019-05-07T12:16:27Z" level=error msg="no AzureAssignedIdentity found for pod:<pod>, <nil>" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.114.5.10
```

It seems someone else has raised the same issue:

https://github.com/Azure/aad-pod-identity/issues/206

**Comment by cwebbtw** [comment] 2019-05-07 15:44
Can confirm that when this behaviour is happening:

```
$ kubectl get azureassignedidentity
No resources found.
```

Deleting the mic pod seems to resolve the problem temporarily.

**Comment by kkmsft** [comment] 2019-05-07 16:22
@cwebbtw - Thank you for further info in this. The messages from NMI indicates that there is no azureassignedidentity created, which you could verify from commandline as well. The creation of azureassignedidentity and the assignment of identity to underlying vm is performed by MIC, so we have to check the MIC verbose logs and see why the assignment is not happening. Since you have found that the hang is seen after find, I am curious to know the info of increased verbosity from MIC around that area.

**Comment by kkmsft** [comment] 2019-05-08 15:12
Apologies if it was not clear - mic is responsible for creating azureassignedidentity. The intend of getting logs there is to understand what is going on in both internal actions - like creating azureassignedidentity and underlying cloud operation like assigning identity to underlying vm.

**Comment by cwebbtw** [comment] 2019-05-22 15:24
Please see, attached, the verbose (v6), logs for this error:

```
+ az login --identity
ERROR: The command failed with an unexpected error. Here is the traceback:

ERROR: 
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 560, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 618, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 611, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 588, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 297, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 461, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 111, in login
    return profile.find_subscriptions_in_vm_with_msi(username, allow_no_subscriptions)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 318, in find_subscriptions_in_vm_with_msi
    msi_creds = MSIAuthentication(resource=resource)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 576, in __init__
    self.set_token()
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 584, in set_token
    token_entry = self._vm_msi.get_token(self.resource)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 632, in get_token
    token_entry = self._retrieve_token_from_imds_with_retry(resource)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 669, in _retrieve_token_from_imds_with_retry
    raise HTTPError(request=result.request, response=result.raw)
requests.exceptions.HTTPError
WARNING: 
To open an issue, please run: 'az feedback'
```

Logs:

```
W0522 15:21:50.895916       1 main.go:29] --kubeconfig not passed will use InClusterConfig
I0522 15:21:50.895991       1 main.go:32] kubeconfig () cloudconfig (/etc/kubernetes/azure.json)
I0522 15:21:50.896127       1 mic.go:52] Starting to create the pod identity client. Version: 0.0.0-dev. Build date: 2019-01-30-18:43
I0522 15:21:50.897077       1 mic.go:61] Cloud provider initialized
I0522 15:21:50.897162       1 mic.go:68] CRD client initialized
I0522 15:21:50.897176       1 mic.go:71] Pod Client initialized
I0522 15:21:50.897285       1 mic.go:90] MIC client starting..
I0522 15:21:50.897348       1 crd.go:156] CRD watchers started
I0522 15:21:50.897366       1 pod.go:61] Wait for cache to sync
I0522 15:21:50.897366       1 mic.go:104] CRD client started
I0522 15:21:50.897530       1 reflector.go:202] Starting reflector *v1.Node (30s) from github.com/Azure/aad-pod-identity/pkg/mic/node.go:27
I0522 15:21:50.897553       1 reflector.go:240] Listing and watching *v1.Node from github.com/Azure/aad-pod-identity/pkg/mic/node.go:27
I0522 15:21:50.897581       1 reflector.go:202] Starting reflector *v1.Pod (30s) from github.com/Azure/aad-pod-identity/pkg/pod/pod.go:70
I0522 15:21:50.897589       1 reflector.go:240] Listing and watching *v1.Pod from github.com/Azure/aad-pod-identity/pkg/pod/pod.go:70
I0522 15:21:50.897955       1 reflector.go:202] Starting reflector *v1.AzureIdentityBinding (10m0s) from github.com/Azure/aad-pod-identity/pkg/crd/crd.go:154
I0522 15:21:50.897978       1 reflector.go:240] Listing and watching *v1.AzureIdentityBinding from github.com/Azure/aad-pod-identity/pkg/crd/crd.go:154
I0522 15:21:50.898465       1 reflector.go:202] Starting reflector *v1.AzureIdentity (10m0s) from github.com/Azure/aad-pod-identity/pkg/crd/crd.go:155
I0522 15:21:50.898481       1 reflector.go:240] Listing and watching *v1.AzureIdentity from github.com/Azure/aad-pod-identity/pkg/crd/crd.go:155
I0522 15:21:50.966485       1 round_trippers.go:405] GET https://mp-ppe-westeurope-r1-k8s-26c8b801.hcp.westeurope.azmk8s.io:443/apis/aadpodidentity.k8s.io/v1/azureidentitybindings?limit=500&resourceVersion=0 200 OK in 68 milliseconds
I0522 15:21:50.967609       1 crd.go:110] Binding created
I0522 15:21:50.968742       1 round_trippers.go:405] GET https://mp-ppe-westeurope-r1-k8s-26c8b801.hcp.westeurope.azmk8s.io:443/apis/aadpodidentity.k8s.io/v1/azureidentitybindings?resourceVersion=9402&timeoutSeconds=454&watch=true 200 OK in 1 milliseconds
I0522 15:21:50.970172       1 round_trippers.go:405] GET https://mp-ppe-westeurope-r1-k8s-26c8b801.hcp.westeurope.azmk8s.io:443/api/v1/nodes?limit=500&resourceVersion=0 200 OK in 71 milliseconds
I0522 15:21:50.974168       1 round_trippers.go:405] GET https://mp-ppe-westeurope-r1-k8s-26c8b801.hcp.westeurope.azmk8s.io:443/api/v1/pods?limit=500&resourceVersion=0 200 OK in 76 milliseconds
I0522 15:21:50.976040       1 round_trippers.go:405] GET https://mp-ppe-westeurope-r1-k8s-26c8b801.hcp.westeurope.azmk8s.io:443/apis/aadpodidentity.k8s.io/v1/azureidentities?limit=500&resourceVersion=0 200 OK in 77 milliseconds
I0522 15:21:50.976362       1 round_trippers.go:405] GET https://mp-ppe-westeurope-r1-k8s-26c8b801.hcp.westeurope.azmk8s.io:443/api/v1/nodes?resourceVersion=26076&timeoutSeconds=544&watch=true 200 OK in 2 milliseconds
I0522 15:21:50.977562       1 crd.go:137] Identity created
I0522 15:21:50.979596       1 round_trippers.go:405] GET https://mp-ppe-westeurope-r1-k8s-26c8b801.hcp.westeurope.azmk8s.io:443/apis/aadpodidentity.k8s.io/v1/azureidentities?resourceVersion=9793&timeoutSeconds=364&watch=true 200 OK in 2 milliseconds
I0522 15:21:50.986649       1 pod.go:42] Pod Created
I0522 15:21:50.986689       1 pod.go:42] Pod Created
I0522 15:21:50.986755       1 pod.go:42] Pod Created
I0522 15:21:50.986768       1 pod.go:42] Pod Created
I0522 15:21:50.986794       1 pod.go:42] Pod Created
I0522 15:21:50.986810       1 pod.go:42] Pod Created
I0522 15:21:50.986942       1 pod.go:42] Pod Created
I0522 15:21:50.986953       1 pod.go:42] Pod Created
I0522 15:21:50.986974       1 pod.go:42] Pod Created
I0522 15:21:50.986988       1 pod.go:42] Pod Created
I0522 15:21:50.986994       1 pod.go:42] Pod Created
I0522 15:21:50.986998       1 pod.go:42] Pod Created
I0522 15:21:50.987001       1 pod.go:42] Pod Created
I0522 15:21:50.987004       1 pod.go:42] Pod Created
I0522 15:21:50.987007       1 pod.go:42] Pod Created
I0522 15:21:50.987011       1 pod.go:42] Pod Created
I0522 15:21:50.987014       1 pod.go:42] Pod Created
I0522 15:21:50.987019       1 pod.go:42] Pod Created
I0522 15:21:50.987022       1 pod.go:42] Pod Created
I0522 15:21:50.987026       1 pod.go:42] Pod Created
I0522 15:21:50.987040       1 pod.go:42] Pod Created
I0522 15:21:50.987045       1 pod.go:42] Pod Created
I0522 15:21:50.987072       1 pod.go:42] Pod Created
I0522 15:21:50.987086       1 pod.go:42] Pod Created
I0522 15:21:50.987091       1 pod.go:42] Pod Created
I0522 15:21:50.987094       1 pod.go:42] Pod Created
I0522 15:21:50.987097       1 pod.go:42] Pod Created
I0522 15:21:50.987100       1 pod.go:42] Pod Created
I0522 15:21:50.987103       1 pod.go:42] Pod Created
I0522 15:21:50.987106       1 pod.go:42] Pod Created
I0522 15:21:50.987110       1 pod.go:42] Pod Created
I0522 15:21:50.987113       1 pod.go:42] Pod Created
I0522 15:21:50.987116       1 pod.go:42] Pod Created
I0522 15:21:50.987119       1 pod.go:42] Pod Created
I0522 15:21:50.987123       1 pod.go:42] Pod Created
I0522 15:21:50.987126       1 pod.go:42] Pod Created
I0522 15:21:50.987129       1 pod.go:42] Pod Created
I0522 15:21:50.987132       1 pod.go:42] Pod Created
I0522 15:21:50.987136       1 pod.go:42] Pod Created
I0522 15:21:50.987139       1 pod.go:42] Pod Created
I0522 15:21:50.987142       1 pod.go:42] Pod Created
I0522 15:21:50.987886       1 round_trippers.go:405] GET https://mp-ppe-westeurope-r1-k8s-26c8b801.hcp.westeurope.azmk8s.io:443/api/v1/pods?resourceVersion=26079&timeoutSeconds=414&watch=true 200 OK in 1 milliseconds
I0522 15:21:50.997576       1 shared_informer.go:123] caches populated
I0522 15:21:50.997588       1 shared_informer.go:123] caches populated
I0522 15:21:50.997612       1 pod.go:66] Pod cache synchronized. Took 100.251942ms
I0522 15:21:50.997616       1 mic.go:111] Node client started
I0522 15:21:50.997636       1 pod.go:72] Pod watcher started !!
I0522 15:21:50.997640       1 mic.go:97] Pod client started
I0522 15:21:50.997647       1 main.go:46] AAD Pod identity controller initialized!!
I0522 15:21:50.997661       1 mic.go:120] Sync thread started.
I0522 15:21:50.997665       1 mic.go:126] Received event: 6
I0522 15:21:51.004608       1 round_trippers.go:405] GET https://mp-ppe-westeurope-r1-k8s-26c8b801.hcp.westeurope.azmk8s.io:443/apis/aadpodidentity.k8s.io/v1/azureidentitybindings 200 OK in 6 milliseconds
I0522 15:21:51.008692       1 round_trippers.go:405] GET https://mp-ppe-westeurope-r1-k8s-26c8b801.hcp.westeurope.azmk8s.io:443/apis/aadpodidentity.k8s.io/v1/azureidentities 200 OK in 3 milliseconds
I0522 15:21:51.012750       1 round_trippers.go:405] GET https://mp-ppe-westeurope-r1-k8s-26c8b801.hcp.westeurope.azmk8s.io:443/apis/aadpodidentity.k8s.io/v1/azureassignedidentities 200 OK in 3 milliseconds
I0522 15:21:51.013919       1 mic.go:176] Found binding match for pod jenkinsdeployer-hmg4t/jenkins-ns with binding jenkins-id-binding
I0522 15:21:51.013942       1 mic.go:182] Looking up id map: jenkins-azure-identity
I0522 15:21:51.013949       1 mic.go:193] identity default/jenkins-azure-identity assigned to jenkins-ns/jenkinsdeployer-hmg4t via default/default
I0522 15:21:51.013954       1 mic.go:400] Making assigned ID: &{{ } {jenkinsdeployer-hmg4t-jenkins-ns-jenkins-azure-identity  default    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] } 0xc000420700 0xc000420380 jenkinsdeployer-hmg4t jenkins-ns aks-agentpool-42571559-3 <nil>} {{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] }  1}}
I0522 15:21:51.014026       1 mic.go:176] Found binding match for pod jenkinsdeployer-l6gjm/jenkins-ns with binding jenkins-id-binding
I0522 15:21:51.014031       1 mic.go:182] Looking up id map: jenkins-azure-identity
I0522 15:21:51.014036       1 mic.go:193] identity default/jenkins-azure-identity assigned to jenkins-ns/jenkinsdeployer-l6gjm via default/default
I0522 15:21:51.014042       1 mic.go:400] Making assigned ID: &{{ } {jenkinsdeployer-l6gjm-jenkins-ns-jenkins-azure-identity  default    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] } 0xc000421c00 0xc000421880 jenkinsdeployer-l6gjm jenkins-ns aks-agentpool-42571559-5 <nil>} {{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] }  1}}
I0522 15:21:51.014070       1 mic.go:339] ok: false, Create added: jenkinsdeployer-hmg4t-jenkins-ns-jenkins-azure-identity
I0522 15:21:51.014076       1 mic.go:339] ok: false, Create added: jenkinsdeployer-l6gjm-jenkins-ns-jenkins-azure-identity
I0522 15:21:51.014081       1 mic.go:362] ok: false, Delete added: jenkinsdeployer-8wd4w-jenkins-ns-jenkins-azure-identity
I0522 15:21:51.014090       1 mic.go:221] del: &[{{AzureAssignedIdentity aadpodidentity.k8s.io/v1} {jenkinsdeployer-8wd4w-jenkins-ns-jenkins-azure-identity  default /apis/aadpodidentity.k8s.io/v1/namespaces/default/azureassignedidentities/jenkinsdeployer-8wd4w-jenkins-ns-jenkins-azure-identity 19c06ad0-7ca5-11e9-8d30-aa2db96ad47d 25862 1 2019-05-22 15:20:15 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] } 0xc0002adc00 0xc0002ad880 jenkinsdeployer-8wd4w jenkins-ns aks-agentpool-42571559-3 <nil>} {{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] }  1}}], add: &[{{ } {jenkinsdeployer-hmg4t-jenkins-ns-jenkins-azure-identity  default    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] } 0xc000420700 0xc000420380 jenkinsdeployer-hmg4t jenkins-ns aks-agentpool-42571559-3 <nil>} {{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] }  1}} {{ } {jenkinsdeployer-l6gjm-jenkins-ns-jenkins-azure-identity  default    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] } 0xc000421c00 0xc000421880 jenkinsdeployer-l6gjm jenkins-ns aks-agentpool-42571559-5 <nil>} {{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] }  1}}]
I0522 15:21:51.014151       1 mic.go:227] Deletion of id: jenkinsdeployer-8wd4w-jenkins-ns-jenkins-azure-identity
I0522 15:21:51.014156       1 crd.go:166] Deletion of id named: jenkinsdeployer-8wd4w-jenkins-ns-jenkins-azure-identity
I0522 15:21:51.060614       1 round_trippers.go:405] DELETE https://mp-ppe-westeurope-r1-k8s-26c8b801.hcp.westeurope.azmk8s.io:443/apis/aadpodidentity.k8s.io/v1/namespaces/default/azureassignedidentities/jenkinsdeployer-8wd4w-jenkins-ns-jenkins-azure-identity 200 OK in 46 milliseconds
I0522 15:21:51.060687       1 mic.go:240] Binding removed: &{TypeMeta:{Kind:AzureIdentityBinding APIVersion:aadpodidentity.k8s.io/v1} ObjectMeta:{Name:jenkins-id-binding GenerateName: Namespace:default SelfLink:/apis/aadpodidentity.k8s.io/v1/namespaces/default/azureidentitybindings/jenkins-id-binding UID:e128794f-7c91-11e9-8d30-aa2db96ad47d ResourceVersion:9402 Generation:1 CreationTimestamp:2019-05-22 13:02:40 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"aadpodidentity.k8s.io/v1","kind":"AzureIdentityBinding","metadata":{"annotations":{},"name":"jenkins-id-binding","namespace":"default"},"spec":{"AzureIdentity":"jenkins-azure-identity","Selector":"jenkins-selector"}}
] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName:} Spec:{ObjectMeta:{Name: GenerateName: Namespace: SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName:} AzureIdentity:jenkins-azure-identity Selector:jenkins-selector Weight:0} Status:{ObjectMeta:{Name: GenerateName: Namespace: SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName:} AvailableReplicas:0}}
I0522 15:21:51.060811       1 mic.go:262] Initiating assigned id creation for pod - jenkinsdeployer-hmg4t, binding - jenkins-id-binding
I0522 15:21:51.060822       1 crd.go:174] Got id jenkinsdeployer-hmg4t-jenkins-ns-jenkins-azure-identity to assign
I0522 15:21:51.060825       1 crd.go:178] Creating assigned Id: jenkinsdeployer-hmg4t-jenkins-ns-jenkins-azure-identity
I0522 15:21:51.061000       1 event.go:218] Event(v1.ObjectReference{Kind:"AzureIdentityBinding", Namespace:"default", Name:"jenkins-id-binding", UID:"e128794f-7c91-11e9-8d30-aa2db96ad47d", APIVersion:"aadpodidentity.k8s.io/v1", ResourceVersion:"9402", FieldPath:""}): type: 'Normal' reason: 'binding removed' Binding jenkins-id-binding removed from node aks-agentpool-42571559-3 for pod jenkinsdeployer-8wd4w
I0522 15:21:51.070505       1 round_trippers.go:405] POST https://mp-ppe-westeurope-r1-k8s-26c8b801.hcp.westeurope.azmk8s.io:443/api/v1/namespaces/default/events 201 Created in 9 milliseconds
I0522 15:21:51.117386       1 round_trippers.go:405] POST https://mp-ppe-westeurope-r1-k8s-26c8b801.hcp.westeurope.azmk8s.io:443/apis/aadpodidentity.k8s.io/v1/namespaces/default/azureassignedidentities 201 Created in 56 milliseconds
I0522 15:21:51.118380       1 cloudprovider.go:132] Find aks-agentpool-42571559-3 in resource group: MC_mp-ppe-westeurope-r1-rg_mp-ppe-westeurope-r1-k8s_westeurope
I0522 15:21:51.373583       1 cloudprovider.go:139] Get of aks-agentpool-42571559-3 completed in 255.186353ms
I0522 15:21:51.994686       1 pod.go:52] Pod Updated
I0522 15:21:56.322994       1 pod.go:52] Pod Updated
I0522 15:21:56.393482       1 pod.go:47] Pod Deleted
I0522 15:22:20.986858       1 reflector.go:286] github.com/Azure/aad-pod-identity/pkg/pod/pod.go:70: forcing resync
I0522 15:22:20.987036       1 pod.go:52] Pod Updated
I0522 15:22:20.987126       1 pod.go:52] Pod Updated
I0522 15:22:20.987148       1 pod.go:52] Pod Updated
I0522 15:22:20.987154       1 pod.go:52] Pod Updated
I0522 15:22:20.987157       1 pod.go:52] Pod Updated
I0522 15:22:20.987160       1 pod.go:52] Pod Updated
I0522 15:22:20.987175       1 pod.go:52] Pod Updated
I0522 15:22:20.987192       1 pod.go:52] Pod Updated
I0522 15:22:20.987198       1 pod.go:52] Pod Updated
I0522 15:22:20.987202       1 pod.go:52] Pod Updated
I0522 15:22:20.987207       1 pod.go:52] Pod Updated
I0522 15:22:20.987210       1 pod.go:52] Pod Updated
I0522 15:22:20.987213       1 pod.go:52] Pod Updated
I0522 15:22:20.987216       1 pod.go:52] Pod Updated
I0522 15:22:20.987219       1 pod.go:52] Pod Updated
I0522 15:22:20.987222       1 pod.go:52] Pod Updated
I0522 15:22:20.987225       1 pod.go:52] Pod Updated
I0522 15:22:20.987228       1 pod.go:52] Pod Updated
I0522 15:22:20.987231       1 pod.go:52] Pod Updated
I0522 15:22:20.987234       1 pod.go:52] Pod Updated
I0522 15:22:20.987237       1 pod.go:52] Pod Updated
I0522 15:22:20.987240       1 pod.go:52] Pod Updated
I0522 15:22:20.987243       1 pod.go:52] Pod Updated
I0522 15:22:20.987246       1 pod.go:52] Pod Updated
I0522 15:22:20.987249       1 pod.go:52] Pod Updated
I0522 15:22:20.987252       1 pod.go:52] Pod Updated
I0522 15:22:20.987254       1 pod.go:52] Pod Updated
I0522 15:22:20.987258       1 pod.go:52] Pod Updated
I0522 15:22:20.987260       1 pod.go:52] Pod Updated
I0522 15:22:20.987263       1 pod.go:52] Pod Updated
I0522 15:22:20.987266       1 pod.go:52] Pod Updated
I0522 15:22:20.987269       1 pod.go:52] Pod Updated
I0522 15:22:20.987272       1 pod.go:52] Pod Updated
I0522 15:22:20.987275       1 pod.go:52] Pod Updated
I0522 15:22:20.987278       1 pod.go:52] Pod Updated
I0522 15:22:20.987281       1 pod.go:52] Pod Updated
I0522 15:22:20.987283       1 pod.go:52] Pod Updated
I0522 15:22:20.987287       1 pod.go:52] Pod Updated
I0522 15:22:20.987293       1 pod.go:52] Pod Updated
I0522 15:22:20.987296       1 pod.go:52] Pod Updated
```

**Comment by cwebbtw** [comment] 2019-05-22 15:28
This is an **intermittent** issue and without making any changes, starts working **eventually**

Our bindings are:

```
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
 name: jenkins-id-binding
spec:
 AzureIdentity: jenkins-azure-identity
 Selector: jenkins-selector
```
and our identity is:

```
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
 name: jenkins-azure-identity
spec:
 type: 0
 ResourceID: <REDACTED>
 ClientID: <REDACTED>
```

**Comment by kkmsft** [comment] 2019-05-23 18:42
From the logs, looks like pod identity is behaving as expected. The intermediate hangs still points to timeouts reaching ARM. @cwebbtw  - Can you please confirm that the above logs are during a hang ? We should see subsequent time out logs in that case. 

/cc @khenidak

**Comment by cwebbtw** [comment] 2019-05-23 22:19
Yes these logs were taken with the corresponding failing `az login --identity` that I've included. Restarting the mic controller temporarily fixes the problem but then it continues to fail shortly after. Eventually it fixes itself entirely and works until the next time. Unfortunately this seems to happen mainly in the afternoon GMT.

**Comment by kkmsft** [comment] 2019-05-23 22:42
Thank you, @cwebbtw . 
Are there other parts of the system (AKS cluster) also facing any such issues around the GMT afternoon time frame ? for example the cloud provider of the k8s cluster performs similar operations, so any cloud operation such as a change in load balancer configuration should hit this issue if it an environment related issue. Any such symptoms are you observing on your cluster ?

**Comment by cwebbtw** [comment] 2019-05-24 08:22
Not that we're observing. We've had a couple of issues with tunnelfront recently but this issue with the identity failures has happened since day 1 on every AKS cluster we build.

**Comment by cwebbtw** [comment] 2019-05-24 08:24
We've had to move away from it now and login with the service principal username and password which works reliably but doesn't feel like the right solution as it exposes the service principal to abuse if the password is obtained.

**Comment by kkmsft** [comment] 2019-05-24 15:35
There are two main operations which happen during this time frame:

Just after this message:
_Find aks-agentpool-42571559-3 in resource group: MC_mp-ppe-westeurope-r1-rg_mp-ppe-westeurope-r1-k8s_westeurope_

we do a GET of the VM to get the current identity information. In the initial messages you provided below:
_I0417 20:10:20.638240       1 cloudprovider.go:132] Find <vm> in resource group: <resource group>
E0417 20:25:58.639157       1 vm.go:48] azure#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded
E0417 20:25:58.639219       1 mic.go:415] azure#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded
E0417 20:25:58.674349       1 mic.go:269] azure#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded_

The call to get has timed out after 15 minutes. During this time window, AAD pod identity was not getting any reply to the GET it sent and eventually the context expires and it goes back to the reconciliation loop which eventually succeeds since it starts a new set of calls which seem to succeed eventually. I suspect this is the same thing seen during the restart, since new calls are being made which works eventually.

In the recent verbose 6 calls, the operation which is happening is when the user assigned identity is being assigned to the vm, which is again an ARM call made to update the VM properties: 

_I0522 15:21:51.373583       1 cloudprovider.go:139] Get of aks-agentpool-42571559-3 completed in 255.186353ms_

I was looking for those logs which should follow this operation, which is some sort of error or context expiry for the CreateOrUpdate calls which was made to assign the user identity from  jenkinsdeployer-hmg4t-jenkins-ns-jenkins-azure-identity on to the VM. Can you please look for those logs later in the messages and provide them ?

One direction is that we will add a healthprobe in future which can potentially restart the operation after a reasonable timeout. Had a question there - how much time out would your application tolerate between its deployment and the user identity being assigned and ready for use ?

Summarizing the two requests above for easy reference:
1. Logs further down indicating a failure or expire of the createorupdate operation in the v6 repro above ?
2. What is the timeout the application can tolerate which will help us in designing a health probe.

Here are two items we can make to proceed:
3.  Please raise and ICM issue with ARM related to the deadline exceeded issue. 
4. I will engage internally with ARM folks as to gather more details.

**Comment by cwebbtw** [comment] 2019-05-31 14:48
@kkmsft 

1. We will re-enable aad-pod-identity on our cluster to get these logs for you as we've reverted to using a service principal log in with a password (undesirable as we don't want to use passwords).

2. See below:

> One direction is that we will add a healthprobe in future which can potentially restart the operation after a reasonable timeout. Had a question there - how much time out would your application tolerate between its deployment and the user identity being assigned and ready for use ?

We retry for up to 2 minutes for the `az login -i` to successfully work and continue to retry throughout that time. We know that restarting the mic controller often brings the process back to life and we are able to work again for a few minutes but then we end up having problems shortly after.

3. We will raise this with our support representatives
4. Fantastic, we also have a contact from Microsoft that is working on this and has apparently identified something that could be of value.

**Comment by cwebbtw** [comment] 2019-06-12 15:30
We have not been able to reproduce this issue on our cluster over the last 2 weeks

**Comment by kkmsft** [comment] 2019-07-03 18:01
@cwebbtw - since the specific issue was root caused to an Azure backend error which has since been fixed. And since the issue was not reproducible now, closing this issue. Kindly feel free to reopen if you think there is more to be investigated here.

**Closed by kkmsft** 2019-07-03 18:01 UTC
