### ISSUE TITLE
AAD Pod Identity takes over five minutes to associate pod IP to assignedIdentity

### ISSUE THREAD

**Issue by johnwatson484** [Azure/aad-pod-identity#1011] opened 2021-03-19 21:13 UTC
We have been working with a Microsoft engineer today to debug this issue.  Here is what we are seeing.

1. We restart the NMI pod at 17:06:26

```
I0319 17:06:26.492320       1 server.go:98] listening on port 2579
W0319 17:06:26.605585       1 iptables.go:123] flushing iptables to add aad-metadata custom chains
```

2. Application pod is deployed at 17:09:19 
3. We confirm that MIC assigns identity to VMSS and there is a corresponding azureassignedidentities resource 
4. We view logs in the application pod, and notice it still has not been able to represent managed identity 
5. NMI logs show the follow errors for 5 minutes: 

```
W0319 17:09:19.488931       1 client.go:208] list pod error: pod list is empty. Retrying, attempt number: 1
W0319 17:09:19.687368       1 client.go:208] list pod error: pod list is empty. Retrying, attempt number: 3
W0319 17:09:19.789216       1 client.go:208] list pod error: pod list is empty. Retrying, attempt number: 2
W0319 17:09:19.987601       1 client.go:208] list pod error: pod list is empty. Retrying, attempt number: 4
W0319 17:09:20.089586       1 client.go:208] list pod error: pod list is empty. Retrying, attempt number: 3
E0319 17:09:20.287836       1 server.go:343] failed to get pod info from pod IP: 172.1.1.39, error: pod list is empty
I0319 17:09:20.288044       1 server.go:192] status (500) took 1201367238 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=172.1.1.39
```
Consistently until 17:13:34 

6. After about 5 minutes, NMI associates the pod IP with the managed identity: 

```
I0319 17:13:34.691220       1 standard.go:73] no clientID or resourceID in request. ffc-demo-dev/ffc-demo-calculation-service-86d74c8ddd-vt782 has been matched with azure identity ffc-demo-dev/ffc-demo-calculation-service-identity
I0319 17:13:34.691324       1 standard.go:179] matched identityType:0 clientid: ##### REDACTED ##### resource:https://servicebus.azure.net/
I0319 17:13:34.759162       1 server.go:192] status (200) took 68005084 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=172.1.1.39
```

7. Application pod begins to work 

5 minute+ delay for the application pod to be able to use managed identity is too long, and we are trying to understand where this is coming from. 

## Additional Context: 
+ AAD Pod Identity Version 1.7.4 
+ K8s version 1.19.6 
+ We can reproduce this on demand by deleting the pod, and then it will take another 5 minutes to re-assign the managed identity
+ In order for the pod to finally get the managed identity, we do not have to restart the MIC or NMI pod. Restarting either one of those pods does not seem to speed up the process. 
+ Since this is a private AKS cluster, we are not going through a firewall to connect to the API server. 
+ VMSS performance and APIserver health all look good  
+ We thought this behavior could be related to this github issue, but does not seem that MIC deletion speeds up the wait: https://github.com/Azure/aad-pod-identity/issues/1009

**Comment by aramase** [comment] 2021-03-19 21:48
Thank you for opening the issue @johnwatson484.

NMI uses the client-go informer client to establish a WATCH connection with the API server. The informer client gets pod create/delete/update events from the API server and populates in the cache. This error `list pod error: pod list is empty. Retrying, attempt number: 1` indicates that NMI hasn't received any events from the API server leaving the cache stale. 

There is an improvement in client-go to implement health checks on existing tcp connection and we've updated to that version as part of [PR](https://github.com/Azure/aad-pod-identity/pull/1010) which will be available in the next release. Restarting the NMI kills the existing TCP connection and establishes a new connection at which all pod events are being sent again.

**Comment by johnwatson484** [comment] 2021-03-20 12:49
> Could you share your AKS cluster fqdn?

Thanks @aramase.

We tried manually killing the NMI pods to see if it prompted the identity to be received faster with no luck.

Where would I find the FQDN?  It's a private cluster.

**Comment by evanlangbehn** [comment] 2021-03-22 13:57
Hello @aramase 

I am the MSFT support engineer that was working with John on this one. I now have an internal repro in the northeurope region that I can demonstrate this behavior on demand. Here is what it looks like: 

1. the 5+ minutes of wait for NMI to get something back from its WATCH command only occurs if we are adding the MSI to the VMSS for the first time. If it is already assigned to VMSS then there is no delay. It does look like MIC assigns the identity very quickly to the VMSS, which does not explain this delay. What I mean by that is portal will show that user assigned identity on the portal in under 30 seconds typically, but we then go on to wait 5-6 minutes for NMI to catch up. 

2. It does not seem like it matters how long NMI had been running previously. The key is here item what is listed above. 

3. Once we deploy a pod that is waiting to use an identity, then if we delete NMI pod as you mentioned it immediately gets the MSI assigned. Deleting the NMI pod just before an app deployment does not help. 

With MSI already assigned to VMSS: 

evan@Azure:~$ kubectl logs demo
I0319 21:03:27.451388       1 main.go:42] starting aad-pod-identity demo pod (namespace: default, name: demo, IP: 10.240.0.18)
I0319 21:03:28.731133       1 main.go:111] successfully acquired a service principal token from 

Without MSI already assigned to VMSS: 

evan@Azure:~$ kubectl logs demo
I0319 21:04:34.558940       1 main.go:42] starting aad-pod-identity demo pod (namespace: default, name: demo, IP: 10.240.0.12)
I0319 21:10:14.743697       1 main.go:111] successfully acquired a service principal token from 

Mitigation: Use the immutable MSI flag during Helm installation of aad-pod-identity to keep the identities assigned to VMSS to avoid the initial 5+ minute delay. 

Based on this info, do you believe the PR you mentioned would still help? It seems like it would which would be good news. I will certainly attempt repro with the newer version once it is released.

**Comment by chewong** [comment] 2021-03-22 18:09
I was able to repro with the steps you provided above:

```log
W0322 17:58:00.479676       1 client.go:208] list pod error: pod list is empty. Retrying, attempt number: 1
W0322 17:58:00.779933       1 client.go:208] list pod error: pod list is empty. Retrying, attempt number: 2
W0322 17:58:01.080204       1 client.go:208] list pod error: pod list is empty. Retrying, attempt number: 3
E0322 17:59:20.479641       1 server.go:371] failed to get matching identities for pod: default/demo, error: context canceled
I0322 17:59:20.479691       1 server.go:192] status (404) took 80000062813 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.0.14
```

With the same cluster, I uninstalled v1.7.4, unassign the user-assigned identity from the VMSS, and built MIC and NMI that included https://github.com/Azure/aad-pod-identity/pull/1010. Here is the result:
```
W0322 18:05:14.338546       1 client.go:208] list pod error: pod list is empty. Retrying, attempt number: 1
W0322 18:05:14.639115       1 client.go:208] list pod error: pod list is empty. Retrying, attempt number: 2
W0322 18:05:14.939730       1 client.go:208] list pod error: pod list is empty. Retrying, attempt number: 3
W0322 18:05:15.240019       1 client.go:208] list pod error: pod list is empty. Retrying, attempt number: 4
W0322 18:06:00.248717       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.19.6/tools/cache/reflector.go:156: watch of *v1.AzurePodIdentityException ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
W0322 18:06:00.248750       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.19.6/tools/cache/reflector.go:156: watch of *v1.AzureAssignedIdentity ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
W0322 18:06:00.248724       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.19.6/tools/cache/reflector.go:156: watch of *v1.Pod ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
I0322 18:06:05.551520       1 standard.go:73] no clientID or resourceID in request. default/demo has been matched with azure identity default/demo
I0322 18:06:05.551617       1 standard.go:179] matched identityType:0 clientid:3207##### REDACTED #####ed02 resource:https://management.azure.com/
I0322 18:06:05.629509       1 server.go:192] status (200) took 51290998165 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.0.16
I0322 18:06:05.766437       1 standard.go:80] clientID in request: 3207##### REDACTED #####ed02, default/demo has been matched with azure identity default/demo
I0322 18:06:05.766493       1 standard.go:179] matched identityType:0 clientid:3207##### REDACTED #####ed02 resource:https://management.azure.com/
I0322 18:06:05.778387       1 server.go:192] status (200) took 12067868 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.0.16
I0322 18:06:05.778929       1 standard.go:80] clientID in request: 3207##### REDACTED #####ed02, default/demo has been matched with azure identity default/demo
I0322 18:06:05.779086       1 standard.go:179] matched identityType:0 clientid:3207##### REDACTED #####ed02 resource:https://management.azure.com/
I0322 18:06:05.787862       1 server.go:192] status (200) took 9031451 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.0.16
```

The demo did run successfully. We are planning to publish a release candidate for v1.7.5, which will include https://github.com/Azure/aad-pod-identity/pull/1010. Would you be able to test it for us?

**Comment by evanlangbehn** [comment] 2021-03-23 12:11
I would be more than happy to test it. Is that something I can test now, or I have to wait for additional items to be updated to have the opportunity to test 1.7.5?

**Comment by chewong** [comment] 2021-03-23 20:56
We have published `v1.7.5-rc.0`. You can run the following commands to test it (assuming you installed the latest aad-pod-identity through helm):
```
helm upgrade aad-pod-identity aad-pod-identity/aad-pod-identity --reuse-values --set mic.tag=v1.7.5-rc.0 --set nmi.tag=v1.7.5-rc.0
```

**Comment by evanlangbehn** [comment] 2021-03-24 11:42
@chewong 

Thank you for the help command. It does seem to resolve this issue. Please see more details below: 

1. Confirmed I was still in repro state with 1.7.4 
2. Installed new container images using helm command provided
3. Confirmed the demo MSI was **not** assigned to VMSS
4. Deployed Demo pod. Previously this would mean 5-6 minutes of wait. 

demo logs: 
I0324 11:36:37.647895       1 main.go:42] starting aad-pod-identity demo pod (namespace: default, name: demo, IP: 10.240.0.13)
I0324 11:37:33.204896       1 main.go:111] successfully acquired a service principal token from http://169.254.169.254/metadata/identity/oauth2/token

It took about 56 seconds to get the MSI / token 

NMI logs: 
W0324 11:35:50.893291       1 iptables.go:123] flushing iptables to add aad-metadata custom chains
W0324 11:36:37.655758       1 client.go:208] list pod error: pod list is empty. Retrying, attempt number: 1
I0324 11:37:32.962783       1 standard.go:73] no clientID or resourceID in request. default/demo has been matched with azure identity default/demo
I0324 11:37:32.962988       1 standard.go:179] matched identityType:0 clientid:2590##### REDACTED #####3f47 resource:https://management.azure.com/
I0324 11:37:32.975856       1 server.go:192] status (200) took 55320143707 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.240.0.13

This does look to fix the issue. Please let me know if you have any concerns with my test or if there is anything else I can help with.

**Comment by chewong** [comment] 2021-03-24 16:13
The log looks good. Thanks for confirming

**Comment by evanlangbehn** [comment] 2021-03-24 19:01
Awesome. Thank you for your help on this one. is there an ETA on release date for 1.7.5?

**Comment by johnwatson484** [comment] 2021-05-23 18:22
Upgrading to 1.7.5 resolved this for us.   No repeat of the issue has occurred since.

**Closed** 2021-05-24 17:28 UTC
Labels: bug
