### ISSUE TITLE
Cloudconfig in /etc/kubernetes/azure.json has "AzurePublicCloud" for customer clouds

### ISSUE THREAD

**Issue by AndyTao0402** [Azure/aad-pod-identity#691] opened 2020-07-18 00:50 UTC
When deploying with customer cloud env file, the cloud config file azure.json has "cloud":"AzureStackCloud". This causes AAD calls Public cloud endpoints instead of endpoints defined in customer cloud env file.

containers:
      - args:
        - --cloudconfig=/etc/kubernetes/azure.json
        - --logtostderr
        - --leader-election-namespace=aad
        env:
        - name: FORCENAMESPACED
          value: "true"
        - name: AZURE_ENVIRONMENT_FILEPATH
          value: /etc/azst/AzureEnvironmentEndpoints.json
        - name: CLOUD
          value: AZURESTACKCLOUD

**Comment by aramase** [comment] 2020-07-18 01:13
@AndyTao0402 MIC reads the cloud name from `/etc/kubernetes/azure.json` and `AZURE_ENVIRONMENT_FILEPATH` is used by the sdk to parse the endpoints list. Not sure what the issue is?

**Comment by AndyTao0402** [comment] 2020-07-18 01:45
MIC reads cloud name from /etc/kubernetes/azure.json, aad-pod-identity calls Public cloud endpoints to fetch token. Public cloud endpoints are not accessable from airgapped clouds, it can only reach the endpoints specified in AZURE_ENVIRONMENT_FILEPATH.  Is there a way we can override the cloud name in  /etc/kubernetes/azure.json?

**Comment by aramase** [comment] 2020-07-20 16:09
@AndyTao0402 `aad-pod-identity` consumes the azure.json file set on the host for AKS or AKS-Engine clusters. If the cloud name is not accurate in the file, then this would be a question for AKS.

**Comment by aramase** [comment] 2020-07-21 17:12
Discussed with @AndyTao0402 offline and this is not a `aad-pod-identity` issue. Closing the issue now. Please feel free to re-open if you have any other questions.

**Closed by aramase** 2020-07-21 17:12 UTC
Labels: bug
