### ISSUE TITLE
Self built NMI image won't start  (MCR image works fine)

### ISSUE THREAD

**Issue by kevinwedwards** [Azure/aad-pod-identity#686] opened 2020-07-14 18:33 UTC
**Describe the bug**
When I deploy MIC and NMI the NMI POD doesn't start... 
mic-76f9b75db5-gz8c8    1/1     Running            0          33s
mic-76f9b75db5-pgnww  1/1     Running            0          33s
**nmi-qvtpm                       0/1     CrashLoopBackOff   2          34s
nmi-tj96x                          0/1     CrashLoopBackOff   2          34s
nmi-v8lb8                         0/1     CrashLoopBackOff   2          34s**

when I run a kubectl log on the pods I get something like the following:
**> kubectl logs nmi-tj96x
flag provided but not defined: -host-ip**
Usage of mic:
  -alsologtostderr
        log to standard error as well as files
  -clientQps float
        Client QPS used for throttling of calls to kube-api server (default 5)
  -cloudconfig string
        Path to cloud config e.g. Azure.json file
  -createDeleteBatch int
        Per node/VMSS create/delete batches (default 20)
  -enableProfile
        Enable/Disable pprof profiling
  -enableScaleFeatures
        Enable/Disable new features used for clusters at scale
  -forceNamespaced
        Forces namespaced identities, binding, and assignment
  -http-probe-port string
        http liveliness probe port (default "8080")
  -immutable-user-msis string
        prevent deletion of these IDs from the underlying VM/VMSS
  -kubeconfig string
        Path to the kube config
  -leader-election-duration duration
        leader election duration (default 15s)
  -leader-election-instance string
        leader election instance name. default is 'hostname' (default "aks-agentpool-34071128-2")
  -leader-election-name string
        leader election name (default "aad-pod-identity-mic")
  -leader-election-namespace string
        namespace to create leader election objects (default "default")
  -log_backtrace_at value
        when logging hits line file:N, emit a stack trace
  -log_dir string
        If non-empty, write log files in this directory
  -logtostderr
        log to standard error instead of files
  -prometheus-port string
        Prometheus port for metrics (default "8888")
  -stderrthreshold value
        logs at or above this threshold go to stderr
  -syncRetryDuration duration
        The interval in seconds at which sync loop should periodically check for errors and reconcile. (default 1h0m0s)
  -v value
        log level for V logs
  -version
        Prints the version information
  -vmodule value
        comma-separated list of pattern=N settings for file-filtered logging

**Steps To Reproduce**
I'm attempting, because of internal cyber-sec policies, to build the MIC and NMI images myself.  If I pull down teh MCR images and install them - they work fine :/

**Expected behavior**
I'd expect the NMI pods to successfully be running like the MIC pods 

**AAD Pod Identity version**
1.5.5

**Kubernetes version**
1.16..9

**Additional context**

FROM golang:1.13.4 AS build
ENV GO111MODULE=on

WORKDIR /go/src/github.com/Azure/aad-pod-identity
COPY go.mod go.mod
COPY go.sum go.sum

RUN apt-get update && apt-get install -y \
  bash \
  git \
  curl \ 
  make \ 
  ca-certificates

_[I do some local CA cert stuff here for our internal auth proxy]_

RUN go mod download
COPY . ./

ARG NMI_VERSION=0.0.0-dev
ARG MIC_VERSION=0.0.0-dev
ARG DEMO_VERSION=0.0.0-dev
ARG IDENTITY_VALIDATOR_VERSION=0.0.0-dev
RUN make build

FROM alpine:3.10.3 AS base
RUN apk update \ 
&& apk upgrade \
&& apk add --no-cache \
    ca-certificates \
    iptables \
    && update-ca-certificates \
    rm -rf /var/cache/apk/*

FROM base AS nmi
COPY --from=build /go/src/github.com/Azure/aad-pod-identity/bin/aad-pod-identity/nmi /bin/
ENTRYPOINT ["nmi"]

FROM base AS mic
COPY --from=build /go/src/github.com/Azure/aad-pod-identity/bin/aad-pod-identity/mic /bin/
ENTRYPOINT ["mic"]

#FROM base AS identityvalidator
#COPY --from=build /go/src/github.com/Azure/aad-pod-identity/bin/aad-pod-identity/identityvalidator /bin/
#ENTRYPOINT ["identityvalidator"]

**Comment by chewong** [comment] 2020-07-14 19:08
https://github.com/Azure/aad-pod-identity/pull/658 removes `--host-ip` flag from NMI. If you remove the `--host-ip` flag from the deployment YAML, it should work.

**Comment by aramase** [comment] 2020-07-14 19:08
@kevinwedwards The `--host-ip` flag has been deprecated in master and will be included in next release. The deployment manifests are updated during release. If you're using the master branch to build NMI, you need to remove the `--host-ip` flag from the daemon set args.

**Comment by kevinwedwards** [comment] 2020-07-14 19:35
I guess that doesn't make sense to me... since I'm using the 1.5.5 tag..

**Comment by kevinwedwards** [comment] 2020-07-14 19:39
I removed the host-ip from teh deployment-rbac.yaml, no change.

A coworker believes that the two entry-points being in the docker file are causing some issues and that the NMI image is somehow starting the MIC container.  which based on the logs, seems possible...     That doesn't make sense to me, but he says he's confident based on using AAD POD ID on his current project and another's team AKS cluster... 

Any thoughts on that?

**Comment by chewong** [comment] 2020-07-14 20:05
Are you using the provided make target to build the binaries and images?

**Comment by kevinwedwards** [comment] 2020-07-14 20:19
For my two build steps: NMI and MIC, I'm doing this in Azure DevOps...  using the docker task using the following:

--target=nmi --build-arg HTTP_PROXY=[proxyaddress] --build-arg HTTPS_PROXY=[proxyaddress] --build-arg NMI_VERSION=$(Build.BuildId)

--target=mic --build-arg HTTP_PROXY=[proxyaddress] --build-arg HTTPS_PROXY=[proxyaddress] --build-arg MIC_VERSION=$(Build.BuildId)

I split up the docker file,  and it seems to be related to what my coworker was saying.  It seem to have worked b/c now i'm seeing the NMI image 'starting'... it still fails, but at least I'm seeing NMI service logs vs MIC logs...


kubectl logs nmi-5zg9p
time="2020-07-14T20:06:20Z" level=info msg="Starting nmi process. Version: 9862. Build date: 2020-07-14-19:50. Log level: info."
time="2020-07-14T20:06:20Z" level=info msg="CRD lite informers started "
time="2020-07-14T20:06:20Z" level=info msg="Initialized health probe on port &[8080]"
time="2020-07-14T20:06:20Z" level=info msg="Started health probe"
time="2020-07-14T20:06:20Z" level=info msg="Registered views for metric%!(EXTRA *[]interface {}=&[])"
time="2020-07-14T20:06:20Z" level=info msg="Starting Prometheus exporter"
time="2020-07-14T20:06:20Z" level=info msg="Registered and exported metrics on port &[9090]"
time="2020-07-14T20:06:20Z" level=info msg="Listening on port 2579"
**time="2020-07-14T20:06:20Z" level=fatal msg="targetip must be set"**

**Comment by chewong** [comment] 2020-07-14 20:26
This error is caused by the lack of `--host-ip` flag. With 1.5.5, it's necessary to provide `--host-ip` flag. Based on your original logs, I thought you are building the images from master branch.

**Comment by kevinwedwards** [comment] 2020-07-14 20:33
I think originally the dual entrypoints were breaking, now upon fixing that, and removing the host-ip... I believe I've introduced a bug. Thank you!  Will revert that change and re-test.

**Closed** 2020-07-14 20:45 UTC
Labels: bug
