### ISSUE TITLE
Can we use AAD Pod Identity feature with hostNetwork = false?

### ISSUE THREAD

**Issue by EhfazR2020** [Azure/aad-pod-identity#1034] opened 2021-04-07 13:45 UTC
**Have you**

- [x] Read [Troubleshooting Guide](../../docs/readmes/README.troubleshooting.md)
- [x] Read [Known Issues](../../docs/readmes/README.known-issues.md)
- [x] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
We are following the recommendations from Azure and one of them is "Usage of host networking and ports should be restricted" under "Restrict unauthorized network access". We were successfully able to apply this for all the pods except for aad-pod-identity ones. As soon as we change the value for **hostNetwork = false** the aad DaemonSet, all the pods gets recreated and our deployment starts failing.

Any help is appreciated even if it's a work around.
**Steps To Reproduce**
Change the value for hostNetwork to false in aad-pod-identity DaemonSet 
**Expected behavior**

**AAD Pod Identity version**
1.7.4
**Kubernetes version**
1.18.10
**Additional context**

**Comment by chewong** [comment] 2021-04-07 16:08
host network is required because NMI intercepts all traffic to IMDS, which is a well-known address to acquire a token on behalf of your workload. See https://docs.microsoft.com/en-us/azure/virtual-machines/linux/instance-metadata-service?tabs=windows for more details.

**Comment by chewong** [comment] 2021-04-12 16:59
Closing this issue since hostNetwork is required by design.

**Closed by chewong** 2021-04-12 16:59 UTC
Labels: bug
