### ISSUE TITLE
Authorization issue using POD identity with Storage

### ISSUE THREAD

**Issue by dewanymca** [Azure/aad-pod-identity#537] opened 2020-03-23 18:16 UTC
Hi Team
We have been using POD identity for enabling MSI feature for Azure resources. We have couple of resource where we want to use this feature- keyvault, storage and service bus. POD identity is working fine with Keyvault (may be because we cache keyvault secret in startup). However seeing erratic behaviour with Azure storage. It works for few request and after that starting giving authorization issue. Any pointer what can be wrong or how to troubleshoot this:

Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
--

Any help will be appreciated

**Comment by aramase** [comment] 2020-03-25 18:23
@dewanymca What is the error you are observing specifically? Is NMI not returning a token on request? Do you see any error messages in the NMI/MIC logs?

**Comment by dewanymca** [comment] 2020-03-26 06:34
below are few logs from storage:

time="2020-03-19T08:08:17Z" level=warning msg="parameter resource cannot be empty" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.1.0.73
time="2020-03-19T08:08:17Z" level=info msg="Status (400) took 236599 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.1.0.73
time="2020-03-19T08:08:17Z" level=info msg="matched identityType:0 clientid:bc37##### REDACTED #####1171 resource:https://storage.azure.com/" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.1.0.73
time="2020-03-19T08:08:17Z" level=info msg="Status (200) took 217846047 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.1.0.73


It's not showing failure logs though. Exception is logged in AI for service..

**Comment by dewanymca** [comment] 2020-03-26 06:41
Just to mention this happens under load

**Comment by aramase** [comment] 2020-03-30 16:20
@dewanymca I would suggest you check the NMI logs at the time the exception is logged in your service. If NMI is returning the token as expected without any errors then I'm not sure if it is an issue with pod-identity.

**Comment by aramase** [comment] 2020-04-03 16:15
@dewanymca Did you get a chance to check the NMI logs during the timeframe the issue is happening?

**Comment by dewanymca** [comment] 2020-04-03 17:12
We were able to reproduce this again. Below are steps:
1) Deployed AKS workload using helm and tested 1 message everything worked fine.
2) After 5 hour, tested message again it failed with Authorization issue. Looking at NMI logs we were seeing 400 error, below are logs:

time="2020-04-03T16:53:41Z" level=warning msg="parameter resource cannot be empty" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.11.0.104
time="2020-04-03T16:53:41Z" level=info msg="Status (400) took 163700 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.11.0.104
time="2020-04-03T16:53:41Z" level=info msg="matched identityType:0 clientid:0c73##### REDACTED #####4b89 resource:https://servicebus.azure.net/" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.11.0.104
time="2020-04-03T16:53:42Z" level=info msg="Status (200) took 145132400 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.11.0.104


POD IP -10.11.0.104

3) deleted pod and new pod came and it started working.

Please help

Thanks
DeepakSanghi

**Comment by aramase** [comment] 2020-04-03 17:19
@dewanymca The first error is `parameter resource cannot be empty` in the request. We have seen this with C# library where the first request is a healthcheck without the resource in the request. The next request from the pod has the `resource` in the request header and the token was successfully returned - 

```
time="2020-04-03T16:53:41Z" level=info msg="matched identityType:0 clientid:0c73##### REDACTED #####4b89 resource:https://servicebus.azure.net/" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.11.0.104
```

**Comment by aramase** [comment] 2020-04-03 17:46
Had an offline discussion about this with @dewanymca. One thing to validate is if there is client side caching of the token as NMI does not perform any caching.

**Comment by aramase** [comment] 2020-04-06 17:29
@dewanymca confirmed there is caching on the client side which means there is no new token fetch calls to NMI. 

Closing this issue as it's not an issue with pod-identity. Please feel free to reopen if you have any questions or other issues.

**Closed by aramase** 2020-04-06 17:29 UTC
